NAME="cxe-tmp"

run:
	# activate a virtual environment using poetry - execute following line in Posix Shell https://python-poetry.org/docs/basic-usage/#activating-the-virtual-environment
	source ~/AppData/Local/pypoetry/Cache/virtualenvs/cxe-tmp-9HDlInaK-py3.10/Scripts/activate ;
	# run poetry wihthin python script main.py
	cd ~/personal/Github/cxe-tmp && poetry run python main.py

help:	
	@echo "${NAME} is currency exchange project, using as reference https://github.com/alexprengere/currencyconverter/tree/master/currency_converter "
	@echo "Illustrative purposes of usage of poetry package"
	@echo "Lines above showing execution of python script using poetry"

# References:
# https://www.dutchengineer.org/path-player?courseid=practical-dataops&unit=practical-dataops_1674372716878_1Unit
# https://dev.to/bowmanjd/getting-started-with-python-poetry-3ica
# https://stackoverflow.com/questions/4377109/shell-script-execute-a-python-program-from-within-a-shell-script
# https://stackoverflow.com/questions/59286983/how-to-run-a-script-using-pyproject-toml-settings-and-poetry
# https://saattrupdan.github.io/2022-08-28-makefu/